### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by CrossEye** [Silverwolf90/game-of-life#1]
> **This is experimental. I would love to hear feedback on both the general style and the code itself.**

Ok, here's some.  I'm about to start my first es6-only project, so I'm quite curious to look at how others are doing this.  Yours is very nicely timed for me.

> Use arrow function syntax.

Absolutely.  One of the great features of es6.

> Use const.

Of course.  Not really a major win, but worth getting in the habit.

> Split the expression into 3 lines. Name. Arguments. Body.

While consistency in a codebase is a good thing, and it's fine if you want to adopt this for your own, I would not choose it, preferring

``` js
const indexes = (array) => range(0, array.length);
```

to this:

``` js
const indexes =
  (array) =>
    range(0, array.length);
```

when the function is short enough.

> Put function decorators (ie: curry(), memoize()) on same line as name.

Yes.  I certainly see no reason to do otherwise.

> Put arguments that act as function parameters first. Arguments should have data as last argument.

I prefer a slightly more nuanced approach, that often amounts to the same thing.  I first saw it described [in Gleb Bahmutov's blog](http://glebbahmutov.com/blog/put-callback-first-for-elegance/) as "Place the arguments LESS likely to change first."

> Functions should be pure (you need a really good reason to not follow this one)

Yes, but there are many good reasons.  The best bet is to segregate the impure code from the pure.

> Function should be one expression. Avoid return.

Nice when you can do it.  But don't make a fetish of it.

> Avoid intermediate variables

Ditto.

> Build functions from smaller functions

Yes, this is one of the core ideas of FP.

> Curry your functions if they have more than argument.

Utility functions, certainly.  But application code?  This is a harder call.  I think you don't need to do this up front.  As long as your `curry` function only expands the invocation possibilities and doesn't alter the existing ones, then you can decide to curry later when you find you need it, and not break existing code.  Then you don't pay the price of `curry` where its not needed.

---

> Are the type signatures as comments useful?

Absolutely.  I would extend this to every function.

> Does this style scale?

Only time will tell, I'm afraid.

> How well are my files/functions/types organized?

I think whatever works for you is fine.  Just be willing to reorganize when your codebase grows.

> Is the pattern for types going over-board? Do they make the code more clear?

I don't think they add a **lot**.  But they are not intrusive.  If they work for you, they're fine.  I certainly buy this choice over function constructors or other OO techniques:

``` js
const Person =
  (firstName, lastName, occupation) => ({
    firstName,
    lastName,
    occupation,
  });
```

> Do you think this is good code? Why or why not?

At first glance, yes.  But it will take more thinking/playing than I've put in so far to become more sure.

> How much would be gained by adding static types using Flow or TypeScript?

In my opinion, very little, but perhaps that's simply because I've _never_ seen a need for them.

> Performance? Lots of wrapped functions means lots more calls. Does it matter?

I worry about that much later.  I design a system with as good code as I can muster, trying not to be stupid about performance, but not letting it drive many decisions.  Then, only if I have performance problems do I work on them, from the most pressing to the least.  Well-written code is easier to refactor/rewrite for performance.

> Should we drop the usage of semi-colons?

Your call, but my choice is still to use them.

**Comment by Silverwolf90** [comment]
> > Split the expression into 3 lines. Name. Arguments. Body.
> 
> While consistency in a codebase is a good thing, and it's fine if you want to adopt this for your own, I would not choose it, preferring

Yeah I'm starting to think it's a bit too extreme. But the consistency is nice. A middle-ground:

``` javascript
const indexes =
  (array) => range(0, array.length);
```

Actually, I might prefer that the best for short functions, preserving the separation of the name and the arrow function expression.

> I prefer a slightly more nuanced approach, that often amounts to the same thing. I first saw it described in Gleb Bahmutov's blog as "Place the arguments LESS likely to change first."

Ah, yes I've heard that before, and I think I prefer it as well. I'll update the readme.

> > Function should be one expression. Avoid return.
> 
> Nice when you can do it. But don't make a fetish of it.
> 
> > Avoid intermediate variables
> 
> Ditto.

Yeah, I think agree with this too. And that this example may have gone  a bit too extreme in this direction.

> > Curry your functions if they have more than argument.
> 
> Utility functions, certainly. But application code? This is a harder call. I think you don't need to do this up front. As long as your curry function only expands the invocation possibilities and doesn't alter the existing ones, then you can decide to curry later when you find you need it, and not break existing code. Then you don't pay the price of curry where its not needed.

Yeah, I'm not necessarily sold on it. But, at least in this example, I found myself needing to curry most functions that had >= 2 arguments. Perhaps consistency is the most important thing. Initially, I found myself causing bugs by using functions that I thought were already curried, and then decided to make the blanket decision of "curry everything".  But likely either approach will work well if you just pick one. Either use the curry decorator when defining the function for everything, or only curry later on as needed. I do agree that utilities should always be curried.

> > Are the type signatures as comments useful?
> 
> Absolutely. I would extend this to every function.

Yes, I think that might be a good idea as well. I initially found them to be a bit cumbersome, and there's always the potential issue of the comment getting out of sync with a change to the actual function. But it solves the problem (or at least makes it less of a problem) that the input to composed functions are being obscured by a lack of type system.

Here's what someone on reddit said about wrapping `flow` in another function to make the input more clear:

> > > > `const someTransformation = (itemsToTransform) => flow( mapOverArray, firstElement, doThingToThatFirstElement, doYetAnotherThing )(itemsToTransform)`
> > > > This thing you have done here is slightly funny to me. You have removed a definition of a function created via a higher-order function and attached to it an arbitrary name which you then supply to the function itself. The thing you have un-wittingly undone here is called "point-free style" and it's part of the powers of expressiveness possible through function composition and partial application.

Do you have any thoughts on that?

> > Performance? Lots of wrapped functions means lots more calls. Does it matter?
> 
> I worry about that much later. I design a system with as good code as I can muster, trying not to be stupid about performance, but not letting it drive many decisions. Then, only if I have performance problems do I work on them, from the most pressing to the least. Well-written code is easier to refactor/rewrite for performance.

I certainly agree with this.

> > Should we drop the usage of semi-colons?
> 
> Your call, but my choice is still to use them.

I lean towards no as well. But the style seems to avoid a lot of syntactical noise, and getting rid of a semi-colons takes that a step further.

**Comment by CrossEye** [comment]
> > I prefer a slightly more nuanced approach, that often amounts to the same thing. I first saw it described in [Gleb Bahmutov's blog](http://glebbahmutov.com/blog/put-callback-first-for-elegance/) as "Place the arguments LESS likely to change first."
> 
> Ah, yes I've heard that before, and I think I prefer it as well. I'll update the readme.

The way I actually usually put it, to account for ordering all parameters is "put the parameters less likely to change before those more likely to change".  Then, so long as you can make this call for every pair of parameters, your order is entirely dictated.  Every now and then you can't; two parameters don't seem to have a clear order; but that's rare.

> Yeah, I'm not necessarily sold on it. But, at least in this example, I found myself needing to curry most functions that had >= 2 arguments. Perhaps consistency is the most important thing. Initially, I found myself causing bugs by using functions that I thought were already curried, and then decided to make the blanket decision of "curry everything".

You won't find me arguing against that.  I'm one of the founders of [Ramda](https://github.com/ramda/ramda), a JS functional programming library that overlaps lodash-fp a great deal (and probably helped prod its existence), although it has a somewhat different focus.  In Ramda, every function of more than one parameter is curried.  So I'm sold.  I simply don't always to this in application code.  I would never actually try to argue you out of it, though.

> > > Are the type signatures as comments useful?
> > 
> > Absolutely. I would extend this to every function.
> 
> Yes, I think that might be a good idea as well. I initially found them to be a bit cumbersome, and there's always the potential issue of the comment getting out of sync with a change to the actual function. But it solves the problem (or at least makes it less of a problem) that the input to composed functions are being obscured by a lack of type system.
> 
> Here's what someone on reddit said about wrapping flow in another function to make the input more clear: [ ...quote elided]

I think they make up a great deal of the lack generated by a missing type system, they serve as much better documentation than JSDoc-style tags, they're short enough to keep easily in sync, and they help me reason about my system.  They're a win all around.  [Ramda's documentation](http://ramdajs.com/docs/) uses them extensively.

I'm with your Reddit interlocutor: I like to write points-free code when I can, when it makes sense, without trying to force it in everywhere.

For instance, this:

``` js
var sum = reduce(add, 0);
```

is much nicer to me than

``` js
var sum = nbrs => reduce(add, 0, nbrs);
```

which is of course much nicer still than the pre-es6 version of

``` js
var sum = function(nbrs) {return reduce(add, 0, nbrs);};
```

I was going to respond to this point about your `flow` technique, which I swear I saw written up at some point, but I didn't notice it in print when I responded, and I dropped it.

All in all, very nice work!

And I'm starting on my code tonight.  Yay!
